# --- Login Page ---
login.username.input=name=username
login.password.input=name=password
login.submit.button=css=button[type='submit']

# --- User Manager Page ---
adduser.add.button=css=i.bi-plus
adduser.role.dropdown=xpath=(//div[@class='oxd-select-wrapper'])[1]
adduser.employee.input=css=input[placeholder='Type for hints...']
adduser.status.dropdown=xpath=(//div[@class='oxd-select-wrapper'])[2]
adduser.username.input=css=input.oxd-input:nth-child(1)
adduser.password.input=xpath=(//input[@class='oxd-input oxd-input--active'])[2]
adduser.confirm.password.input=xpath=(//input[@type='password'])[2]
adduser.save.button=xpath=//button[@type='submit']

# --- Add User Page (Dynamic Templates) ---
adduser.dropdown.option.template=//div[contains(@class, 'oxd-select-option')]//span[normalize-space(text())='%s']
adduser.employee.suggestion.template=//div[@role='option']//span[contains(text(), '%s')]

# --- User Management Page ---
usermgmt.admin.link=link=Admin
usermgmt.table.rows=xpath=//div[@class='oxd-table-body']//div[@role='row']
usermgmt.table.cells=class=oxd-table-cell

# --- Header Layer ---
header.upgrade.button=xpath=//button[text()= ' Upgrade']
